### ISSUE TITLE
Plugin doesn't work after install

### ISSUE THREAD

**Issue by thms122** [Sytm/waypoints#29]
**Describe the bug**
Both plugins I need are loaded and show when I do /pl. I can tab commands but when I enter them I get no response. In console it says: "Shinee__ issued server command: /waypoints". I gave my role every waypoints permission and also I'm OP.

**To Reproduce**
I downloaded Md5Lukas-Commons and Waypoints
Steps to reproduce the behavior (example):
1. waypoints folder appears
2. tried several /waypoints commands
3. added every permission
4. reinstalled

**Expected behavior**
I exptect to get a menu or a list wich commands I can use or an error feedback.

**Server environment(please complete the following information):**
- I'm hosting on MC-Host24 so I dont have a clue

**Additional context**
My Plugins: BetterSleeping3, LuckPerms, Md5Lukas-Commons, Minepacks, DeadChest, ChairStairs, Waypoints

**Comment by Sytm** [comment]
No error messages or anything like that? Because it should never happen that no message is sent. Also check the log at server startup / reload.

**Comment by Sytm** [comment]
No replies for a prolonged amount of time, closing.
